### ISSUE TITLE
ipv6 on .ane

### ISSUE THREAD

**Issue by amihanya** [myflashlab/webView-ANE#120]
hi,

I get reject from Apple that say my app don't support ipv6, I ask a forums about this, and I get answer to check my .ane. you can see the post and answer here:

https://forums.adobe.com/thread/2165212

I use on my app:

com.myflashlab.air.extensions.webView<

 did you use URLMonitor  in your code? did you now about this reject ?

thanks!

**Comment by myflashlab** [comment]
We'll look into this as this is new. In the meanwhile, please check this link: http://stackoverflow.com/questions/38565109/how-to-use-uiwebview-that-supports-ipv6

**Comment by amihanya** [comment]
i saw this link, but the answer ther its Apple dont check the server they check if your app can support to load ipv6.
if its help this is the reject from apple (i can send you the .crash file):
We were unable to review your app as it crashed on launch. We have attached detailed crash logs to help troubleshoot this issue.

Next Steps

Please revise your app and test it on a device while connected to an IPv6 network (all apps must support IPv6) to ensure it will launch without crashing.

Resources

For additional information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and Supporting IPv6-only Networks.

For a networking overview, please see About Networking.

For information on how to symbolicate and read a crash log, please see Tech Note TN2151 Understanding and Analyzing iPhone OS Application Crash Reports.

If you have difficulty reproducing this issue, please try testing the workflow described in Testing Workflow with Xcode's Archive feature.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

**Comment by myflashlab** [comment]
We are testing our ANEs against IPv6 now. please hold on till we get back to you with the test results.

**Comment by myflashlab** [comment]
Alright, we setup a [ipv6 network](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html) and ran our demo RichWebview app on that. It worked fine! and no, we are not using ```URLMonitor```. Yet, here are some guesses/hints that might help you locate the problem:

1. When they tested your app, it failed at launch time, are you initializing the ANE at launch time?
2. Not directly related, but have you added [NSAppTransportSecurity](http://stackoverflow.com/questions/32663122/ios-9-and-nsapptransportsecurity) to your manifest if you are accessing ```http``` addresses?
3. you are not using ipv4 standard addresses in your app, are you? something like: ```000.000.000.000```?

From experience, apple is crazy! :D maybe you should contact them more and ask them to be more exact? this guy [here](https://forums.developer.apple.com/thread/48170#142313) for example, had his app approved with no change! Or even one of our users [here](https://github.com/myflashlab/inAppPayments-ANE/issues/22#issuecomment-247713602).

I think you should try to find an answer somewhere else in your app not the ANE. and besides, no one else has reported something similar, so that's very probable that the problem is from somewhere else.

**Comment by amihanya** [comment]
thanks! 

1.yes i init all the ane when the app load.
2.if i ask from http i dont need to use NSAppTransportSecurity?
3.i check...

thanks!

**Comment by amihanya** [comment]
2.if i ask from http i dont need to use NSAppTransportSecurity?

**Comment by myflashlab** [comment]
Turning off the ```NSAppTransportSecurity``` thing is necessary if you are loading unsecured addresses begin with ```http```.

**Comment by myflashlab** [comment]
We'd like to know how you're doing regarding this issue...?

**Comment by amihanya** [comment]
I send to apple and wait to review, i hope the app pass it.

**Comment by myflashlab** [comment]
Good, please update us with the news also.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
