### ISSUE TITLE
Get HTML DOM of openWebViewURL in AS3 (any URL).

### ISSUE THREAD

**Issue by Joint-Force** [myflashlab/webView-ANE#123]
I need to get information from the HTML DOM of pages loaded into the RichWebView with openWebViewURL. I don't own all the pages the user will see so I can't add in functions or can I?

This might have to do with the same issue, this line of code doesn't seem to work.
_ex.callJS("AirBridge.evoke('back_at_you');");
It never sends anything to AS3.

**Comment by myflashlab** [comment]
You are basically asking to have the option to inject JavaScript into different 3rd-party pages you are loading with RichWebview, right?

Because if you have control over the html content, you can easily add the required methods by the ANE but if you don't, then being able to inject JS functions may help you.

This is a good idea and I am marking this issue so we can release a new version of the ANE with the ability to inject custom JS functions to loaded pages.

**Comment by Joint-Force** [comment]
That sounds like it would work for me. Thanks.


I'll want to be running multiple lines of JavaScript. In addition to callJS(String), It would be useful to allow .js files to be run with callJS(File).
`
var js_file:File = File.applicationStorageDirectory.resolvePath("example.js");
_ex.callJS(js_file);
`
It would help me stay organized. Maybe someone knows a good way of writing lots of JS in AS3 that I'm not aware of.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
