### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Cyrillix** [myflashlab/webView-ANE#14]
I would like to try your web view in order to test an maybe use on our projetc, but I only have blank page under console interface, no ok button to clic on it.

I have build apk, and execute it on Xperia Z3 Android 5.1.1

**Comment by myflashlab** [comment]
you mean you can't run the demo .apk? https://github.com/myflashlab/webView-ANE/tree/master/FD/dist

if you are building the apk yourself, you should first try to build from the sample FlashDevelop or FlashBuilder projects.

in any case, we won't be able to help if you are not posting any error messages!

**Comment by Cyrillix** [comment]
I can install demo.apk and launch it , but it only display Rich WebView header and debug console,with no special log in it. That-s with i try to rebuild it with the same issue

**Comment by myflashlab** [comment]
Do you have this problem on this specific device? or it's the same in your other devices?

**Comment by Cyrillix** [comment]
i'll try and keep you inform

**Comment by Cyrillix** [comment]
So in fact, it's working on my phone, sorry for this wrong issue. 

Which android version do you support? I have tried on 2.3.6 and the demo is crashing, i think this version si too old

**Comment by myflashlab** [comment]
Actually it works on 2.3.6 too but not all the features depending on what Javascript you are using... that's why we have provided the sdkVersion property. so you can tell your JS which Android is running it so you can customize your JS logic...

to get started with Android 2.3.6 try loading a very simple html file with no video tags specially. (video tags are supported on newer HTML5 versions which Android 2.3.6 is not very comfortable with!)

**Comment by Cyrillix** [comment]
OK I'll try.

I still have one question, do you handle view resize on soft keyboard display ?  On my project with your ane, my bottom toolbar is hidden by the keyboard with StageWebView is working. it could be nice to have it 

Thanks

**Comment by myflashlab** [comment]
could you send us a screenshot to see the difference?
