### ISSUE TITLE
Need flashvars from html to be able to load swf

### ISSUE THREAD

**Issue by DanielSLeblanc** [myflashlab/webView-ANE#151]
I need an app that can load html and swf.
The RichWebView works perfectly with the html, but when swfobject.embedSWF(...) is called nothing happens (obviously since html can't load a swf).
So, what I need is access to the variables in the jsp page.  Specifically I need the flashvars.
This is the only detail missing to use AIR to correctly load the swf.

**Comment by Sigil2014** [comment]
Managed to do this with a workaround with inline javascript.  Any suggestions or improvements are welcome:
1) Looped through the variables and added them to a string
2) Separated with separators each key and value from the object
3) Returned the string to as3
4) Split the string into arrays and built the flashVars object

AS3 CODE:

private const ITEM_SEPARATOR:String = "|^^|";
private const VALUE_SEPARATOR:String = "|~~|";
private const GET_FLASHVARS_FUNC_NAME:String = "getFlashvarsFromJS";
private var flashVars:Object;

private function onPageFinished(e:RichWebViewEvent):void {
        //inline javascript so nothing needs to be added to the html page
        //this function fails unless the javascript flashvars object is called "flashVars"
        //if it doesn't find the variable it fails silently, and the app is unaffected (which is great)
        _ex.callJS("var variables = String('');for (var name in flashVars){variables+=String(name)+String('"+VALUE_SEPARATOR+"')+String(flashVars[name])+String('"+ITEM_SEPARATOR+"');}AirBridge.evoke('"+GET_FLASHVARS_FUNC_NAME+"('+String(variables)+')');");
}
		
public function getFlashvarsFromJS(...vars):void {
	//the vars I received were not what I expected or needed
}

//used RichWebView API to capture the flashvars' concatenated string
private function onReceivedMessage(e:RichWebViewEvent):void {
	closeWebView();
	var flashvarString:String = (e.param as String).substring(GET_FLASHVARS_FUNC_NAME.length+1,  (e.param as String).length-1-ITEM_SEPARATOR.length);
	var flashVars:Obect = getFlashvarsFromJSString(flashvarString);
       //dispatched the flashVars to the rest of the application which is now in charge of loading the swf
	dispatchEvent(new SwfPageEvent(SwfPageEvent.HTML_PAGE_READY, flashVars));
	
	DynamicFunc.run(this, e.param);
}

private function getFlashvarsFromJSString(jsMessage:String):Object{
	trace("getFlashvarsFromJSArray="+jsMessage);
	var flashvarsArray:Array = jsMessage.split(ITEM_SEPARATOR);
	var flashVars:Object = new Object();
	for (var i:int=0;i<flashvarsArray.length;i++) {
		var flashvarsGroup:Array = String(flashvarsArray[i]).split(VALUE_SEPARATOR);
		var flashvarKey:String = flashvarsGroup[0];
		var flashvarValue:String = flashvarsGroup[1];
                flashVars[flashvarKey] = flashvarValue;
        }
        return flashVars;
}


Hope this helps to improve this already great ANE!

**Comment by myflashlab** [comment]
Please provide some more information on how you are loading an swf in your content? this is surely not happening on iOS side, right? it will help if you can send us a URL with sample html/js/swf codes so we can run and test this locally also.

**Comment by Sigil2014** [comment]
Just to be clear I managed to get this to work and added the code in the
forum.

I included a sample of the html.  Flashvars used to be considered the
standard method for sending parameters to Flash.

I used the javascript function that I added in the forum to request the
flashvars from the page.  The function failed silently if there isn't
flashvars variable in the html, so if the function returns a value I parse
the flashvars.

After getting the flashvars from javascript I send the value
of flashVars.simulatorFile to the class responsible for adding swf files,
and call closeWebView().

I then load the swf with that name using a SwfLoader component in AIR.
There are a number of methods to load swf, but this is the simplest.  It
works easily on Android, but for now I am still looking for a method to
load into iOS because of their security restrictions.  Below is a simple
method with SwfLoader:

                                var simulatorSwfLoader:SwfLoader = new
SwfLoader();
var loaderContext:LoaderContext = new LoaderContext(false,
ApplicationDomain.currentDomain, null);
loaderContext.allowLoadBytesCodeExecution = true;
loaderContext.allowCodeImport = true;
simulatorSwfLoader.loaderContext = loaderContext;
simulatorSwfLoader.isPopUp = true;
simulatorSwfLoader.loadForCompatibility = false;
simulatorSwfLoader.trustContent = true;
simulatorSwfLoader.maintainAspectRatio = true;
simulatorSwfLoader.scaleContent = false;
simulatorSwfLoader.source = serverUrl+flashVars.simulatorFile;
                                addElement(simulatorSwfLoader);

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
