### ISSUE TITLE
How do i get response using the EMBEDDED BROWSER?

### ISSUE THREAD

**Issue by babakasol** [myflashlab/webView-ANE#154]
I am using the RichwebView ANE for embedded browser but not able to get the response. Also want to know when will "RichWebViewEvent.EMBEDDED_BROWSER_ACTION" will show any response?

**Comment by myflashlab** [comment]
What do you mean by "not able to get the response"? If you are on iOS and you are trying to open an http address, you must [add the following to your manifest](https://github.com/myflashlab/webView-ANE/blob/master/FD/application.xml#L62-L65):

```xml
<key>NSAppTransportSecurity</key>  
<dict>  
	<key>NSAllowsArbitraryLoads</key><true/>  
</dict>
```

on iOS, ```RichWebViewEvent.EMBEDDED_BROWSER_ACTION``` happens when you hit the share button in the safariviewcontroller and happens on Android when you click on any of the menu items or the action button.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
