### ISSUE TITLE
the ane simply do not work for me.

### ISSUE THREAD

**Issue by jabirraju** [myflashlab/webView-ANE#159]
i purchased ane http://www.myflashlabs.com/product/rich-webview-ane-adobe-air-native-extension/ and it simply do not work. it do not render a simple website whereas the website was working with native stagewebview code. i send a mail via your web form with code but no reply yet. you can see source code and generated apk at **[sensitive information removed]**
generated apk simply do not install in samsung tab 2 and it installed in my Panasonic phone but installed app do not open at all.

**Comment by myflashlab** [comment]
@jabirraju  You are not allowed to distribute our ANEs (licensed or demo versions) in public locations. This is strictly prohibited. I have flagged your username and you can contact us about this issue at http://www.myflashlabs.com/contact/ while linking to this page. If this happens again, you will be hard banned from our services permanently.

1. I was not able to install your .apk and I can see that you have built for x86 only! If you want to run an .apk on a device, you usually need to build for armeabi-v7a
2. I also checked your manifest .xml file and noticed that you have not modified your manifest at all! have you read the documentation? https://github.com/myflashlab/webView-ANE#air-xml-manifest
3. This ANE (like all our other ANEs) will NOT work on simulators. you need to run them on a real device.

ANEs, unlike the core AS3 libraries, need to be implemented in your project before they can correctly function. Have you watched our tutorial videos on YouTube? https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

Overall, it seems like you are very new with using ANEs in your projects. here are my suggestions:
First try to watch some tutorials about how ANEs are used. There are many samples if you google this topic. Then, make sure you are reading the documentation available on our GitHub repository and also make sure you are setting up everything in your project based on the sample demo project we have provided in our repository.

If none of the above helped you, you can always contact us to schedule a Skype/Teamviewer session with one of our experts to teach you how things are setup.

Considering that this issue is too general and you're project setup is too far away from being able to run ANY ANE, I am closing this issue. If you have more specific questions, feel free to open a new issue.
