### ISSUE TITLE
back keyboard Event

### ISSUE THREAD

**Issue by SherarVeRoked** [myflashlab/webView-ANE#167]
My app contains pages that do not include the webView but the back keyboard Event doesnt wrok, when ever I take off the webView it wroks. In addition, I could not work with the back event listener. any solution? thanks,

**Comment by myflashlab** [comment]
This is the expected behavior. Whenever the webview is present, (or the Surface Video Player ANE) the native window will hijack the device back button. You need to listen to the ANE's back button pressed event for as long as the ANE is not removed. There doesn't seem to be a better solution for this.
