### ISSUE TITLE
Webpage always defaults to reading mode (No images)

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/webView-ANE#218]
Any reason why when the webpage loads it's always in the reading / text only mode? Is there a way to completely disable that even being an option ?

**Comment by myflashlab** [comment]
you may find this useful: https://stackoverflow.com/questions/14688030/setting-webview-to-view-desktop-site-and-not-mobile-site

**Comment by jonathonpitman** [comment]
How does this apply to this ANE ?

**Comment by myflashlab** [comment]
Well, the ANE is using native code behind the scene so the solutions introduced in the given link could be useful to you also. 

First, about how JavaScript is designed on the target webpage: If you have access to the webpage, you can modify the JS so it will load the desktop page instead of mobile version. (Notice: we are no JS expert and you should search online for more details on this regard)

Second, and probably the better solution, would be to fool the website about who is accessing the page by changing the useragent of the webview by setting the property ```RichWebViewSettings.USER_AGENT``` before opening the page. again, do some Googling to know what user agent value would be appropriate for this.

**Comment by myflashlab** [comment]
Can you share what url you are trying to load?

**Comment by jonathonpitman** [comment]
Not publicly unfortunately :(

**Comment by myflashlab** [comment]
please send it [here](http://www.myflashlabs.com/contact/) while linking back to this issue number.

**Comment by jonathonpitman** [comment]
Sent you the URL.  You'll see 2 submissions. The first submission I sent you has a URL that contains the %2 in it related to issue #219 you are investigating. 

The second submission is a version of the URL without the %2 that you can use for testing this issue regarding the reding mode being set regardless of what User Agent is set.

Thanks for looking in to this.

**Comment by jonathonpitman** [comment]
Any progress with this ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
