### ISSUE TITLE
Animate movement of Webview / cache issue

### ISSUE THREAD

**Issue by nohraay** [myflashlab/webView-ANE#23]
Hi,
it's possible to animate the in / out of the webview (x or y)?. ex: using TweenMax
And can we cache the data loaded? 

Thank you in advance

**Comment by nohraay** [comment]
I didn't get any reply

**Comment by myflashlab** [comment]
Hi @nohraay yes, of course. you can set the position of the rich webview with any tween library like Tweenmax for example. or even the onEnterFrame listener.

hint: if you are using a tween lib to animate the webview, you should consider not to change the width and height of the webview too often simply because each time you change that, your html/js code will try to adapt to the new dimention which will probably freez your app if it's happening too often. but changing x,y can happen quickly with no problem at all.

**Comment by nohraay** [comment]
Thank you, but please can you send me the way I can write the function "webView.setPosition" inside the TweenMax because I tried, and it failed

**Comment by myflashlab** [comment]
TweenMax can not only change object's properties but it can also change one number to another number with its ease options. search for how tweenMax can tween numbers... and while it's doing that, you can put a listener to it to grab the changing number and there call the setPosition method of the webview.

**in our todo-list we are going to add x,y,width,height properties to the webview instance so the positioning thing can happen a lot easier.**

**Comment by nohraay** [comment]
Ok I will wait for the update and now will search for a solution with like you said
Thank you

**Comment by myflashlab** [comment]
Happy Building Flash Apps :)
