### ISSUE TITLE
Example Screenshot please

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/webView-ANE#53]
Hi I would like to load my website off screen then take a screenshot of it off screen. Then animate the snapshot in, or fade it in, and then unload it and replace my snapshot with the actual loaded content. 

How can we do this?

**Comment by myflashlab** [comment]
Well, that can happen exactly as you described and there's already an animation example from the screenshot in the demo project. You can check out the demo and see how that works. The only advice I can give is that always try to initialize The RichWebview once in your project as long as possible because it will take far less time to load new content than initializing a new instance.

So, when you load your content first in the webview off screen, keep it off screen for as long as you wish then bring it in where you like, when you like.

Even when you don't need it in your current app page, don't dispose it if you know it will be used shortly again. Just keep it off screen.

**Comment by myflashlab** [comment]
Let me know if there's anything else we can help you with? or we should close this ticket as resolved?

**Comment by PapaDeBeau** [comment]
Hi, I was kind if hoping for an example. I tried the demo and it does not fit my needs. 

For example it takes a screenshot of the entire website. I just need a shot in the demnsions of the device width and height.

 Also, it can't call on the page loaded as I hoped. I get errors. 

Finally I checked the documents and there is very very little info on screenshot. If you could provide a quick example of the above mentioned that would be great.  Thanks

**Comment by myflashlab** [comment]
in the current version, RichWebview takes a screenshot from the whole html page. with the next release we are planning to add current view screenshots.  

> Also, it can't call on the page loaded as I hoped. I get errors. 

I'm not sure I understand the problem here. please elaborate.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
