### ISSUE TITLE
Problems with iOS

### ISSUE THREAD

**Issue by phihochzwei** [myflashlab/webView-ANE#6]
Hi there, 

when trying to include the ANE in our project and compile an IPA, I receive the following: 

<img width="1058" alt="bildschirmfoto 2015-07-17 um 15 59 20" src="https://cloud.githubusercontent.com/assets/10193885/8758769/ef51ff28-2c9c-11e5-8e03-a9834f56bb66.png">

Also, when I try to run it on the Simulator, I get: 

exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name command.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at com.doitflash.air.extensions.webView.ios::Ios()
at com.doitflash.air.extensions.webView::MyWebView()...

Anyone an idea on that ?

**Comment by myflashlab** [comment]
That's because you are using more than one extension in your project. to fix this issue all you have to do is to make sure that the "Hide ANE-Library-Symbols" check box is checked under the "Native Extensions" tab in "ActionScript Build Packaging" menu in your FlashBuilder.

some of our extensions also use common library dependencies. you know if its needed if there is a readme.txt in the lib folder of demo projects. for more information about these common dependencies, you may check here: https://github.com/myflashlab/common-dependencies-ANE
