### ISSUE TITLE
Moving application in background on back button

### ISSUE THREAD

**Issue by dani2003** [myflashlab/webView-ANE#64]
How do I disable the back button in the webview?
I want to move the application to the background when you click on the back button.

**Comment by myflashlab** [comment]
When webview opens up, it will take over the device's back button. let me talk about this with the rest of the team and I'll get back to you. Thanks for bringing this to our attention anyhow.

**Comment by myflashlab** [comment]
This is not directly related to the RichWebView ANE and we are thinking to add it on a seperated ANE because other users may need it even if they are not using the RichWebView. Anyway, please try this ANE: [richWebView.zip](https://github.com/myflashlab/webView-ANE/files/139104/richWebView.zip)

There is a new property ```moveAndroidTaskToBack()``` which will show the Android home page when called!

you may use it when the WebView is running or even if it does not. if it's running, listen for the back button event being clicked ```RichWebViewEvent.BACK_CLICKED```

```actionscript
_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);
private function onBackClicked(e:RichWebViewEvent):void
{
	var result:Boolean = _ex.moveAndroidTaskToBack();
	C.log("moveTaskToBack result = " + result);
}
```

Let me know how it goes.

**Comment by myflashlab** [comment]
Please upgrade to V6.1.0 and this problem is solved. Please feel free to reopen the issue if you have more questions about this.

**Comment by galaxybeing** [comment]
Excuse my ignorance on this.  Normally hitting the back button will go back to the last page?
And if I call this, the whole app moves to the background?  What if I want it to move to the background only when there are no more pages in the page stack?

**Comment by myflashlab** [comment]
As said in my last post, you should listen to ```_ex.addEventListener(RichWebViewEvent.BACK_CLICKED, onBackClicked);```

and in the ```onBackClicked``` function, you can decide on all you described above.

```actionscript
function onBackClicked(e:RichWebViewEvent):void
{
    if (_ex.canGoBack) _ex.goBack();
    else _ex.closeWebView();
    
    // Or do the other thing?!
    // var result:Boolean = _ex.moveAndroidTaskToBack();
    // trace("moveTaskToBack result = " + result);
}
```

**Comment by galaxybeing** [comment]
You’re right!!!  Sorry, late at night up here.  Thanks for doing such a great job on these ANEs.  I hope I can keep getting work using them.  :)
